apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    type: frontend
spec:
  containers:
    - name: app
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 200m
          memory: "500Mi"
        limits:
          cpu: 5
          memory: "5Gi"