apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-ingress
  labels:
    name: student-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mysv-lb
                port:
                  number: 8081
