apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    type: frontend
spec:
  containers:
    - name: app
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 100m
          memory: 500Mi
        limits:
          cpu: 1
          memory: 1Gi