---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: default
spec:
  encryptedData:
    password: AgA8AG2OQoV2dgxkgxfaObtqIXa9FpdEW6OALUqElmX8yLBxLTXJyZerVZb8qRY/rEVEm+NW4Q0pbreQisLt/g4aULCUup73AkxogowgIBZK0NHS9sZxNnpJHDRWAjFk+zHev86/KyQ6vISAZQ9p3m6Uuj59RWQxDljSt1LjMiPMiiasABTveUg5+myWsf/BsjeJXIEhohozxnRrqoEIg85lA0kjcemsV0FAm69jQ1LyA2fuIFORGCeg7oKXJ3zQ5DUgYjIxswhaJ/bCegbNNEm1AYGn6jXGVp5E+iRZ14ASUsNiu8THS+ouT620WAaFXoX8gtzl9051Obqq0ZR1uAjkXM861Cu65SxPwfA2OxLDCSAT9uK+jR8GKfmx75KQc0XhifXgnumMCneHCzBJSpE89jHMVZRZtu5qH3ifYFga/H+sdyQNoXzD9qAJ9HBGDMFlshMj0brq/pBZNuSkA23gJLDrx4Fcns0YgWp6rILUmchf2faNPbuAFXrPGbSw0kpIB0W+RRi12jmUxvwQ1WMoLgQQeoqCCFpgNDPgex3mWl+hjX+P3kzZtO/2XhG841BnSxVtuNRUa/1GMSXfDPj9XGSUlk6xCtAPKaS+dLuS8OmMPpl1RYfRwx5LCTMgUfkXD+sJclpHT91YVLeGTOEe70ue18GYGSY5OtlUfYy51PKTxiZ8JUX8jckEoFeUFkUfFPOKwHbx0N/M
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: default
