apiVersion: v1
kind: ConfigMap
metadata:
  name: test-{{ .Release.Name }}
  labels:
  {{- include "mychart.labels" . | indent 4 }}
data:
  {{- range $key,$val := .Values.dbconfig}}
  {{ $key }}: {{ $val | quote }}
  {{- end }}