apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.wordpressPv.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.wordpressPv.scName }}
  capacity:
    storage: 1Gi
  accessModes:
    - {{ .Values.wordpressPv.accessMode }}
  hostPath:
    path: {{ .Values.wordpressPv.hostPath }}
