apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.wordpressPv.name }}
  labels:
{{- include "wordpress.vol.labels" . | indent 4 }}
spec:
  storageClassName: {{ .Values.wordpressPv.scName }}
  capacity:
    storage: 1Gi
  accessModes:
    - {{ .Values.wordpressPv.accessMode }}
  hostPath:
    path: {{ .Values.wordpressPv.hostPath }}
