apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.wordpressPvc.name }}
  labels:
{{- include "wordpress.vol.labels" . | indent 4 }}
spec:
  storageClassName: {{ .Values.wordpressPvc.scName }}
  accessModes:
    - {{ .Values.wordpressPvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.wordpressPvc.capacity }}
