apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: myapp
    image: nginx
    ports:
    - containerPort: 80
  - name: tom
    image: tomcat
    ports:
    - containerPort: 8080
