apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-08f70c10383a50b84
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
                - ap-south-1a
                - ap-south-1b
                - ap-south-1c
