apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: studentdb
  name: studentdb
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentdb
  template:
    metadata:
      labels:
        app: studentdb
    spec:
      containers:
        - image: mongo
          name: db
          resources:
            requests:
              cpu: 1
              memory: "1Gi"
            limits:
              cpu: 2
              memory: "2Gi"
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - mongosh
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-cm
                  key: mongodb-root-uname
            - name: MONGO_INITDB_ROOT_PASSWORD
              # value: test123
              valueFrom:
                secretKeyRef:
                  name: mongodb-sec
                  key: mongodb-root-pass
          volumeMounts:
            - mountPath: /data/db
              name: data-store
      volumes:
        - name: data-store
          persistentVolumeClaim:
            claimName: mongo-data-claim
