apiVersion: v1
kind: ConfigMap
metadata:
  name: test-{{ .Release.Name }}
  labels:
{{- include "tomnginx.lables" . | indent 4 }}
data:
  {{- range $key,$val := .Values.dbconfig }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}