apiVersion: v1
kind: Pod
metadata:
  name: efs-pod-2
spec:
  containers:
    - name: app-container-2
      image: nginx:latest
      volumeMounts:
        - mountPath: "/shared-data"
          name: efs-volume
  volumes:
    - name: efs-volume
      persistentVolumeClaim:
        claimName: efs-pvc-static

---

apiVersion: v1
kind: Pod
metadata:
  name: efs-pod-3
spec:
  containers:
    - name: app-container-2
      image: nginx:latest
      volumeMounts:
        - mountPath: "/shared-data"
          name: efs-volume
  volumes:
    - name: efs-volume
      persistentVolumeClaim:
        claimName: efs-pvc-static
  nodeName: ip-192-168-20-213.ap-south-1.compute.internal
