apiVersion: v1
kind: Service
metadata:
  name: mysv-cip
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: datastore

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: datastore
  name: datastore-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datastore
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: datastore
    spec:
      containers:
      - image: 8072388539/datastore:v31.0
        name: datastore
#        livenessProbe:
#          httpGet:
#            path: /test
#            port: 80
#          initialDelaySeconds: 3
#          periodSeconds: 3
#          timeoutSeconds: 4
#          failureThreshold: 3
