apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/scrape: "true"
  name: mysv-cip
spec:
  ports:
    - port: 8081
      targetPort: 8082
  selector:
    app: datastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: datastore
  name: datastore-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datastore
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: datastore
    spec:
      containers:
      - image: 8072388539/datastore:v34.0
        name: datastore
#        livenessProbe:
#          httpGet:
#            path: /test
#            port: 80
#          initialDelaySeconds: 3
#          periodSeconds: 3
#          timeoutSeconds: 4
#          failureThreshold: 3
