apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-volume-static-rom
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: fs-0391b1a4dde49fbe9.efs.ap-south-1.amazonaws.com
    path: /
  mountOptions:
    - ro
