apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
  - kind: Group
    name: "developer"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io

# mapRoles:
# mapUsers:
#   - userarn: arn:aws:iam::975050065855:user/shivagande
#     username: shivagande
#     groups:
#     - developer
