apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: testapp
          image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1
              memory: "1Gi"
