apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappone
  labels:
    type: webapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: webapp
    spec:
      containers:
        - name: mywebapp
          image: nginx:1.27.1-alpine-perl
  replicas: 10
  selector:
    matchLabels:
      type: webapp
  strategy:
    type: Recreate
