apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-job
spec:
  template:
    spec:
      containers:
        - name: myjob
          image: ubuntu
          command: ["sh", "-c", "sleep 5"]
      restartPolicy: Never
# if the pod created by job fails then job retries it for 3 number of times.
#  backoffLimit: 3
#  #after how many number of successful completions the job marked as completed.
#  completions: 4
  #if the pod created by job runs more than 10 seconds then it will go to deadlineexceed state.
#  activeDeadlineSeconds: 10
  #after the 30 seconds of job completion the job gets deleted.
#  ttlSecondsAfterFinished: 30
  #this will create the parallel pods to complete the job until completions.
#  parallelism: 2
