apiVersion: v1
kind: Service
metadata:
  name: eip-svc
spec:
#  selector:
#    name: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 49152
  externalIPs:
    - 198.51.100.32