apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    type: webapp
spec:
  replicas: 20
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: app
          image: nginx
          ports:
            - containerPort: 80
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - webapp
                      - app
              topologyKey: kubernetes.io/hostname
