apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    type: webapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: webapp
    spec:
      containers:
        - name: mywebapp
          image: nginx
  replicas: 10
  selector:
    matchLabels:
      type: webapp
