apiVersion: batch/v1
kind: CronJob
metadata:
  name: test
spec:
  schedule: "* * * * *" #every minute
  # 0 8 * * *
  # permission to run concurrent jobs that are allowed to run at any given time.
  # allowed values:
  # Allow(default) -> to allow the concurrent execution of jobs.
  # Forbid -> restricts the job until the old job gets completed.
  # Replace -> stops the currently running job and creates the new job.
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: test
              image: 8072388539/goldmetal:v2.0
              env:
                - name: GOLD_API_ACCESS_TOKEN
                  value: goldapi-c6dnsm1hap1sa-io
          restartPolicy: OnFailure
#      backoffLimit: 3