apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  labels:
    type: webapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: webapp
    spec:
      containers:
        - name: mywebapp
          image: nginx:stable-perl
        - name: tom
          image: tomcat
  replicas: 3
  selector:
    matchLabels:
      type: webapp
