apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 20
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: app
          image: nginx
          ports:
            - containerPort: 80
      tolerations:
        - key: "a"
          operator: "Equal"
          value: "b"
          effect: "NoSchedule"
