apiVersion: apps/v1
kind: Deployment
metadata:
  name: untolorated-webapp
spec:
  replicas: 20
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: app
          image: nginx
          ports:
            - containerPort: 80