apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-cr
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"] #["get", "list", "watch", "create", "update", "patch", "delete"]
