apiVersion: v1
kind: ConfigMap
metadata:
  name: test-{{ .Release.Name }}
  labels:
  {{- include "webapp.labels" . | indent 4 }}
data:
  {{- range $key,$val := .Values.dbconfig }}
  {{ $key }}: {{ $val | repeat 5 | quote }}
  {{- end }}