apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: cd
                operator: In
                values:
                  - db
        - weight: 100
          preference:
            matchExpressions:
              - key: ae
                operator: In
                values:
                  - bz
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
