apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysqlPv.name }}
  labels:
{{- include "mysqlPv.labels" . | indent 4}}
spec:
  {{- with .Values.mysqlPv }}
  storageClassName: {{ .scName }}
  capacity:
    storage: {{ .capacity }}
  accessModes:
    - {{ .accessMode }}
  hostPath:
    path: {{ .hostPath }}
  {{- end }}