apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlSvc.name }}
  labels:
    app: mysql
spec:
  ports:
    - port: {{ .Values.mysqlSvc.svcPort }}
      targetPort: {{ .Values.mysqlSvc.targetPort }}
  selector:
{{- include "mysql.labels" . | indent 4}}
