apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysqlPvc.name }}
  labels:
{{- include "mysqlPvc.labels" . | indent 4 }}
spec:
  {{- with .Values.mysqlPvc }}
  storageClassName: {{ .scName }}
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .capacity }}
  {{- end }}
