apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysqlPvc.name }}
spec:
  storageClassName: {{ .Values.mysqlPvc.scName }}
  accessModes:
    - {{ .Values.mysqlPvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysqlPvc.capacity }}
