apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: wordpress
{{- include "wordpress.labels" . | indent 4 }}
spec:
  {{- with .Values.wordpressDeploy }}
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:{{ .imageTag }}
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_NAME
              value: mysql
          ports:
            - containerPort: {{ .containerPort }}
              name: wordpress
          resources:
          {{- toYaml .containerResources | nindent 12 }}
          livenessProbe:
          {{- toYaml .livenessProbe | nindent 12 }}
          readinessProbe:
          {{- toYaml .livenessProbe | nindent 12 }}
          startupProbe:
          {{- toYaml .livenessProbe | nindent 12 }}
          volumeMounts:
            - name: wp-volume
              mountPath: /var/www/html
      volumes:
        - name: wp-volume
          persistentVolumeClaim:
            claimName: {{ .pvcName }}
  {{- end }}
