apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappone
  labels:
    type: app
    app: test
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: app
    spec:
      containers:
        - name: mywebapp
          image: nginx
        - name: webserver
          image: tomcat
  replicas: 3
  selector:
    matchLabels:
      type: app

---
apiVersion: v1
kind: Service
metadata:
  name: multiport-svc
spec:
  type: NodePort
  selector:
    type: app
  ports:
    - name: nging-port
      port: 80
      protocol: TCP
      targetPort: 80
    - name: tomcat-port
      port: 8080
      protocol: TCP
      targetPort: 8080
