apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-app
  labels:
    type: webapp
    app: test
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: webapp
    spec:
      containers:
        - name: mywebapp
          image: 8072388539/gymapp:v1
          ports:
          - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      type: webapp

---
apiVersion: v1
kind: Service
metadata:
  name: gymapp-svc
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 80
  selector:
    type: webapp
