apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    type: frontend
spec:
  containers:
#    - name: app
#      image: busybox
#      command: ["sh", "-c", "sleep 10"]
    - name: app
      image: nginx