apiVersion: v1
kind: Pod
metadata:
  name: busybox-app
  labels:
    type: web
spec:
  restartPolicy: OnFailure
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 10"]