apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
    - name: myapp
      image: nginx
  initContainers:
    - name: test
      image: busybox
      command: ["nslookup","https://www.google.com"]