#apiVersion: v1
#kind: Pod
#metadata:
#  name: init-pod
#spec:
#  containers:
#    - name: myapp
#      image: nginx
#      volumeMounts:
#        - mountPath: /data
#          name: db-store
#  initContainers:
#    - name: bb
#      image: busybox
#      command: ["sh","-c","chmod 777 /data"]
#      volumeMounts:
#        - mountPath: /data
#          name: db-store
#  volumes:
#    - name: db-store
#      hostPath:
#        path: /data

apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
    - name: myapp
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: db-store
  initContainers:
    - name: webapp
      image: 8072388539/k8s-init-container:v1.0
      env:
        - name: AWS_ACCESS_KEY_ID
          value: <AWS_ACCESS_KEY_ID>
        - name: AWS_SECRET_ACCESS_KEY
          value: <AWS_SECRET_ACCESS_KEY>
        - name: S3_BUCKET_NAME
          value: testing-init-containers
      volumeMounts:
        - mountPath: /data
          name: db-store
  volumes:
    - name: db-store
      hostPath:
        path: /data
