apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
    - name: myapp
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: db-store
  initContainers:
    - name: bb
      image: busybox
      command: ["sh","-c","chmod 777 /data"]
      volumeMounts:
        - mountPath: /data
          name: db-store
  volumes:
    - name: db-store
      hostPath:
        path: /data
