mysqlDeploy:
  name: mysql
  imageTag: 5.6
  containerPort: 3306
  mountPath: /var/lib/mysql
  pvcName: mysql-pvc

mysqlSvc:
  name: mysql
  svcPort: 3306
  targetPort: 3306

mysqlPvc:
  name: mysql-pvc
  scName: manual
  accessMode: ReadWriteOnce
  capacity: 1Gi

mysqlPv:
  name: mysql-pv
  scName: manual
  capacity: 1Gi
  accessMode: ReadWriteOnce
  hostPath: /mnt/data

mysqlConfig:
  secret: bXlzcWxteXNxbA==