apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: student-app
  name: student-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
#      imagePullSecrets:
#        - name: dockerhubsecret
      containers:
        - name: studentapp
          image: 8072388539/studentstore:v2.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: student-cm
                  key: mongodb-endpoint
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: student-cm
                  key: mongodb-port
            - name: MONGODB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: student-cm
                  key: mongodb-dbname
            - name: MONGODB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: student-cm
                  key: mongodb-uname
            - name: MONGODB_PASSWORD
              value: test123
          resources:
            requests:
              cpu: 1
              memory: "1Gi"
            limits:
              cpu: 2
              memory: "2Gi"
          livenessProbe:
             httpGet:
               path: /getStudents
               port: 8080
             initialDelaySeconds: 3
             periodSeconds: 3
             timeoutSeconds: 4
             failureThreshold: 3
          readinessProbe:
             httpGet:
               path: /getStudents
               port: 8080
             initialDelaySeconds: 3
             periodSeconds: 3
             timeoutSeconds: 4
             failureThreshold: 3
          startupProbe:
             httpGet:
               path: /getStudents
               port: 8080
             initialDelaySeconds: 3
             periodSeconds: 3
             timeoutSeconds: 4
             failureThreshold: 3
