apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    type: webapp
spec:
  containers:
    - name: webapp
      image: tomcat:{{ .Values.global.imgVersion }}
      ports:
        - containerPort: {{ .Values.tomcat.port }}