apiVersion: v1
kind: Pod
metadata:
  name: student-app
spec:
  imagePullSecrets:
    - name: dockerhubsecret
  containers:
    - name: student-app
      image: 8072388539/ubuntu-volume:v1.0
      ports:
        - containerPort: 8080
