apiVersion: v1
kind: Pod
metadata:
  name: mymachine
spec:
  restartPolicy: Never
  containers:
    - name: machine
      image: ubuntu
      volumeMounts:
        - mountPath: /data
          name: data-volume
  initContainers:
    - name: git-repo-clone
      image: 8072388539/ubuntu-git
      command: ["git clone https://github.com/bitnami-labs/sealed-secrets.git"]
      volumeMounts:
        - mountPath: /data
          name: data-volume
  volumes:
    - name: data-volume
      hostPath:
        path: /data/unique/
        type: Directory
