apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-db-pass
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "mysql-creds"
        objectType: "secretsmanager"
        objectAlias: "mysql-root-password"
