apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    type: webapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: webapp
    spec:
      containers:
        - name: mywebapp
          image: nginx:latest
  replicas: 3
  selector:
    matchLabels:
      type: webapp
  strategy:
    type: Recreate
