apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappnew
  labels:
    type: newwebapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: newwebapp
    spec:
      containers:
        - name: mywebapp
          image: nginx:stable-perl #v2
  replicas: 3
  selector:
    matchLabels:
      type: newwebapp
