wordpressDeploy:
  name: wordpress-app
  replicaCount: 1
  imageTag: 4.8-apache
  containerPort: 80
  pvcName: wordpress-pvc
  containerResources:
    requests:
      cpu: 0.2
      memory: "500Mi"
    limits:
      cpu: 0.4
      memory: "600Mi"
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 3
    periodSeconds: 3
    timeoutSeconds: 4
    failureThreshold: 3

wordpressPvc:
  name: wordpress-pvc
  scName: manual
  accessMode: ReadWriteOnce
  capacity: 1Gi

wordpressPv:
  name: wordpress-pv
  scName: manual
  accessMode: ReadWriteOnce
  hostPath: /var/www/html

wordpressSvc:
  name: wordpress-svc
  svcPort: 8080
  targetPort: 80

appIngress:
  name: wordpress-ingress
  ingressType: kong
  svcName: wordpress-svc
  svcPort: 8080