wordpressDeploy:
  name: wordpress-app
  replicaCount: 1
  imageTag: 4.8-apache
  containerPort: 80
  pvcName: wordpress-pvc
wordpressSvc:
  name: wordpress-svc
  svcPort: 8080
  targetPort: 80
wordpressPvc:
  name: wordpress-pvc
  scName: manual
  accessMode: ReadWriteOnce
  capacity: 1Gi
wordpressPv:
  name: wordpress-pv
  scName: manual
  accessMode: ReadWriteOnce
  hostPath: /var/www/html
mysqlDeploy:
  name: mysql
  imageTag: 5.6
  containerPort: 3306
  mountPath: /var/lib/mysql
  pvcName: mysql-pvc
mysqlSvc:
  name: mysql
  svcPort: 3306
  targetPort: 3306
mysqlPvc:
  name: mysql-pvc
  scName: manual
  accessMode: ReadWriteOnce
  capacity: 1Gi
mysqlPv:
  name: mysql-pv
  scName: manual
  capacity: 1Gi
  accessMode: ReadWriteOnce
  hostPath: /mnt/data
appIngress:
  name: wordpress-ingress
  ingressType: kong
  svcName: wordpress-svc
  svcPort: 8080
