apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    type: webapp
spec:
  selector:
    matchLabels:
      type: webapp
  replicas: 3
  template:
    metadata:
      labels:
        type: webapp
    spec:
      containers:
        - name: app
          image: nginx
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /test
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3  #default value 10 sec
            timeoutSeconds: 4  #default value 1 sec. Probe will fail if probe did not get the response within 4 seconds.
            failureThreshold: 3 #default value is 3.

---
apiVersion: v1
kind: Service
metadata:
  name: probe-svc
spec:
  selector:
    type: webapp
  ports:
    - port: 80
      targetPort: 80
