apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    type: webapp
spec:
  selector:
    matchLabels:
      type: webapp
  replicas: 3
  template:
    metadata:
      labels:
        type: webapp
    spec:
      containers:
        - name: app
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /demo
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 4
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: probe-svc
spec:
  selector:
    type: webapp
  ports:
    - port: 80
      targetPort: 80
