apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "uat-test"
  region: "ap-south-1"
  version: "1.23"

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 3
    volumeSize: 30
#    privateNetworking: true
    ssh:
      publicKeyName: jdk