apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "uat-dev"
  region: "us-east-1"
  version: "1.29"

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 3
    volumeSize: 30
    privateNetworking: true
    ssh:
      publicKeyName: jdk