apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        reloader.stakater.com/match: "app-config,app-secret"
      labels:
        app: mysql
    spec:
      containers:
        - name: mydb
          image: mysql
          env:
            - name: MYSQL_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mysqlusername
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: password
          ports:
            - containerPort: 3306
#          volumeMounts:
#            - name: mysql-volume
#              mountPath: /var/lib/mysql
#      volumes:
#        - name: mysql-volume
#          persistentVolumeClaim:
#            claimName: mysql-pvc

  If I update configmap in kubernetes, Should the pods should be restarted to render the  changes? Do we have any other way otherthan restarting
