apiVersion: v1
kind: Pod
metadata:
  name: student-app-tom
  namespace: monitoring
spec:
#  imagePullSecrets:
#    - name: dockerhubsecret
  containers:
    - name: student-app
      image: nginx
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent
