apiVersion: v1
kind: Pod
metadata:
  name: student-app-two
spec:
#  imagePullSecrets:
#    - name: dockerhubsecret
  containers:
    - name: student-app
      image: ubuntu
      imagePullPolicy: Never
